apiVersion: apps/v1
kind: Deployment
metadata:
  name: nepai-frontend
  namespace: nepai
  labels:
    app: nepai-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nepai-frontend
  template:
    metadata:
      labels:
        app: nepai-frontend
    spec:
      containers:
      - name: frontend
        image: pulami/nepai-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
