name: Deploy NepAI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write .env file
        run: |
          cat << EOF > .env
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL }}
          NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
          NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          UPSTASH_REDIS_URL=${{ secrets.UPSTASH_REDIS_URL }}
          EOF

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Deploy with PM2
        run: |
          export PATH=$PATH:/usr/bin
          pm2 delete nepai --silent || true
          pm2 start ecosystem.config.js --env production
          pm2 save